-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema KAWKI_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KAWKI_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KAWKI_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `KAWKI_DB` ;

-- -----------------------------------------------------
-- Table `KAWKI_DB`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`CATEGORIAS` (
  `CATEGORIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL COMMENT 'Derby\nOxford',
  PRIMARY KEY (`CATEGORIA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPOS_COMPROBANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPOS_COMPROBANTE` (
  `TIPO_COMPROBANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Boleta\nFactura',
  PRIMARY KEY (`TIPO_COMPROBANTE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPOS_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPOS_USUARIO` (
  `TIPO_USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL COMMENT 'Cliente\nVendedor\nAdministrador',
  PRIMARY KEY (`TIPO_USUARIO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`USUARIOS` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APE_PATERNO` VARCHAR(50) NOT NULL,
  `DNI` VARCHAR(15) NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  `CODIGO` VARCHAR(10) NOT NULL,
  `NOMBRE_USUARIO` VARCHAR(50) NOT NULL,
  `CONTRASENHA` VARCHAR(255) NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TIPO_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `FK_USUARIOS_TIPOS_USUARIO` (`TIPO_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_USUARIOS_TIPOS_USUARIO`
    FOREIGN KEY (`TIPO_USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`TIPOS_USUARIO` (`TIPO_USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPOS_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPOS_CONDICION` (
  `TIPO_CONDICION_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Cantidad mínima de productos\nMonto mínimo de compra',
  PRIMARY KEY (`TIPO_CONDICION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPOS_BENEFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPOS_BENEFICIO` (
  `TIPO_BENEFICIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Descuento por porcentaje \nDescuento fijo\nEnvío gratis',
  PRIMARY KEY (`TIPO_BENEFICIO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`DESCUENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`DESCUENTOS` (
  `DESCUENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `TIPO_CONDICION_ID` INT NOT NULL,
  `VALOR_CONDICION` INT NOT NULL COMMENT 'ej. \"3 productos\", \"S/ 200\"',
  `TIPO_BENEFICIO_ID` INT NOT NULL,
  `VALOR_BENEFICIO` INT NOT NULL COMMENT 'ej. \"15%\" o \"S/ 30\"',
  `FECHA_INICIO` DATETIME NOT NULL,
  `FECHA_FIN` DATETIME NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`DESCUENTO_ID`),
  INDEX `FK_DESCUENTOS_TIPOS_CONDICION` (`TIPO_CONDICION_ID` ASC) VISIBLE,
  INDEX `FK_DESCUENTOS_TIPOS_BENEFICIO` (`TIPO_BENEFICIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_DESCUENTOS_TIPOS_CONDICION`
    FOREIGN KEY (`TIPO_CONDICION_ID`)
    REFERENCES `KAWKI_DB`.`TIPOS_CONDICION` (`TIPO_CONDICION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DESCUENTOS_TIPOS_BENEFICIO`
    FOREIGN KEY (`TIPO_BENEFICIO_ID`)
    REFERENCES `KAWKI_DB`.`TIPOS_BENEFICIO` (`TIPO_BENEFICIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`VENTAS` (
  `VENTA_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TOTAL` DECIMAL(10,2) NOT NULL,
  `FECHA_HORA_ULTIMO_ESTADO` DATETIME NOT NULL,
  `DESCUENTO_ID` INT NULL,
  PRIMARY KEY (`VENTA_ID`),
  INDEX `FK_VENTAS_USUARIOS` (`USUARIO_ID` ASC) VISIBLE,
  INDEX `FK_VENTAS_DESCUENTOS` (`DESCUENTO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_VENTAS_USUARIOS`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`USUARIOS` (`USUARIO_ID`),
  CONSTRAINT `FK_VENTAS_DESCUENTOS`
    FOREIGN KEY (`DESCUENTO_ID`)
    REFERENCES `KAWKI_DB`.`DESCUENTOS` (`DESCUENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`METODOS_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`METODOS_PAGO` (
  `METODO_PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Tarjeta bancaria\nYape\nPlin',
  PRIMARY KEY (`METODO_PAGO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`COMPROBANTES_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`COMPROBANTES_PAGO` (
  `COMPROBANTE_PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TIPO_COMPROBANTE_ID` INT NOT NULL,
  `NUMERO_SERIE` VARCHAR(50) NOT NULL,
  `DNI_CLIENTE` VARCHAR(8) NULL,
  `NOMBRE_CLIENTE` VARCHAR(100) NULL,
  `RUC_CLIENTE` VARCHAR(11) NULL,
  `RAZON_SOCIAL_CLIENTE` VARCHAR(100) NULL,
  `DIRECCION_FISCAL_CLIENTE` VARCHAR(200) NULL,
  `TELEFONO_CLIENTE` VARCHAR(9) NULL,
  `TOTAL` DECIMAL(10,2) NOT NULL,
  `VENTA_ID` INT NOT NULL,
  `METODO_PAGO_ID` INT NOT NULL,
  PRIMARY KEY (`COMPROBANTE_PAGO_ID`),
  UNIQUE INDEX `NUMERO_SERIE` (`NUMERO_SERIE` ASC) VISIBLE,
  INDEX `FK_COMPROBANTES_PAGO_TIPOS_COMPROBANTE` (`TIPO_COMPROBANTE_ID` ASC) VISIBLE,
  INDEX `FK_COMPROBANTES_PAGO_VENTAS` (`VENTA_ID` ASC) VISIBLE,
  INDEX `FK_COMPROBANTES_PAGO_METODOS_PAGO` (`METODO_PAGO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_COMPROBANTES_PAGO_TIPOS_COMPROBANTE`
    FOREIGN KEY (`TIPO_COMPROBANTE_ID`)
    REFERENCES `KAWKI_DB`.`TIPOS_COMPROBANTE` (`TIPO_COMPROBANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPROBANTES_PAGO_VENTAS`
    FOREIGN KEY (`VENTA_ID`)
    REFERENCES `KAWKI_DB`.`VENTAS` (`VENTA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPROBANTES_PAGO_METODOS_PAGO`
    FOREIGN KEY (`METODO_PAGO_ID`)
    REFERENCES `KAWKI_DB`.`METODOS_PAGO` (`METODO_PAGO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`ESTILOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`ESTILOS` (
  `ESTILO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Charol\nClásicos\nCombinados\nMetalizados',
  PRIMARY KEY (`ESTILO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PRODUCTOS` (
  `PRODUCTO_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  `CATEGORIA_ID` INT NOT NULL,
  `ESTILO_ID` INT NOT NULL,
  `PRECIO_VENTA` DECIMAL(10,2) NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCTO_ID`),
  INDEX `FK_PRODUCTOS_CATEGORIAS` (`CATEGORIA_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_ESTILOS` (`ESTILO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTOS_CATEGORIAS`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `KAWKI_DB`.`CATEGORIAS` (`CATEGORIA_ID`),
  CONSTRAINT `FK_PRODUCTOS_ESTILOS`
    FOREIGN KEY (`ESTILO_ID`)
    REFERENCES `KAWKI_DB`.`ESTILOS` (`ESTILO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`COLORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`COLORES` (
  `COLOR_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Blanco \nCamel \nMarrón \nPiel \nCeleste \nCrema \nBeige \nNegro \nAmarillo \nPlata \nAzul \nRosado \nGris \nRojo \nTurquesa \nAcero \nVerde ',
  PRIMARY KEY (`COLOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TALLAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TALLAS` (
  `TALLA_ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL COMMENT '35\n36\n37\n38\n39',
  PRIMARY KEY (`TALLA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PRODUCTOS_VARIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PRODUCTOS_VARIANTES` (
  `PROD_VARIANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `SKU` VARCHAR(45) NOT NULL,
  `STOCK` INT NOT NULL,
  `STOCK_MINIMO` INT NOT NULL,
  `ALERTA_STOCK` TINYINT(1) NULL,
  `PRODUCTO_ID` INT NOT NULL,
  `COLOR_ID` INT NOT NULL,
  `TALLA_ID` INT NOT NULL,
  `VALOR_BENEFICIO` INT NULL,
  `URL_IMAGEN` VARCHAR(300) NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DISPONIBLE` TINYINT(1) NOT NULL,
  PRIMARY KEY (`PROD_VARIANTE_ID`),
  INDEX `FK_PRODUCTOS_VARIANTES_PRODUCTOS` (`PRODUCTO_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_VARIANTES_COLORES` (`COLOR_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_VARIANTES_TALLAS` (`TALLA_ID` ASC) VISIBLE,
  UNIQUE INDEX `SKU_UNIQUE` (`SKU` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_PRODUCTOS`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS` (`PRODUCTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_COLORES`
    FOREIGN KEY (`COLOR_ID`)
    REFERENCES `KAWKI_DB`.`COLORES` (`COLOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_TALLAS`
    FOREIGN KEY (`TALLA_ID`)
    REFERENCES `KAWKI_DB`.`TALLAS` (`TALLA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`DETALLE_VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`DETALLE_VENTAS` (
  `DETALLE_VENTA_ID` INT NOT NULL AUTO_INCREMENT,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNITARIO` DECIMAL(10,2) NOT NULL,
  `SUBTOTAL` DECIMAL(10,2) NOT NULL,
  `VENTA_ID` INT NOT NULL,
  `PROD_VARIANTE_ID` INT NOT NULL,
  PRIMARY KEY (`DETALLE_VENTA_ID`),
  INDEX `FK_DETALLE_VENTAS_VENTAS` (`VENTA_ID` ASC) VISIBLE,
  INDEX `FK_DETALLE_VENTAS_PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_VENTAS_VENTAS`
    FOREIGN KEY (`VENTA_ID`)
    REFERENCES `KAWKI_DB`.`VENTAS` (`VENTA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DETALLE_VENTAS_PRODUCTOS_VARIANTES`
    FOREIGN KEY (`PROD_VARIANTE_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPOS_MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPOS_MOVIMIENTO` (
  `TIPO_MOVIMIENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NOT NULL COMMENT 'Ingreso\nSalida\nAjuste',
  PRIMARY KEY (`TIPO_MOVIMIENTO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`MOVIMIENTOS_INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`MOVIMIENTOS_INVENTARIO` (
  `MOV_INVENTARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `CANTIDAD` INT NOT NULL,
  `FECHA_HORA_MOV` DATETIME NOT NULL,
  `OBSERVACION` VARCHAR(200) NULL,
  `TIPO_MOVIMIENTO_ID` INT NOT NULL,
  `PROD_VARIANTE_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`MOV_INVENTARIO_ID`),
  INDEX `FK_MOV_INVENTARIO_TIPOS_MOVIMIENTO` (`TIPO_MOVIMIENTO_ID` ASC) VISIBLE,
  INDEX `FK_MOVIMIENTOS_INVENTARIO_PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID` ASC) VISIBLE,
  INDEX `FK_MOVIMIENTOS_INVENTARIO_USUARIOS` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_MOV_INVENTARIO_TIPOS_MOVIMIENTO`
    FOREIGN KEY (`TIPO_MOVIMIENTO_ID`)
    REFERENCES `KAWKI_DB`.`TIPOS_MOVIMIENTO` (`TIPO_MOVIMIENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MOVIMIENTOS_INVENTARIO_PRODUCTOS_VARIANTES`
    FOREIGN KEY (`PROD_VARIANTE_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MOVIMIENTOS_INVENTARIO_USUARIOS`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERTS PARA TABLAS MAESTRAS

-- TIPO_USUARIO
INSERT INTO TIPOS_USUARIO (nombre) VALUES
('Vendedor'),
('Administrador');

-- CATEGORIAS
INSERT INTO CATEGORIAS (nombre) VALUES
('Derby'),
('Oxford');

-- ESTILOS
INSERT INTO ESTILOS (nombre) VALUES
('Charol'),
('Clásicos'),
('Combinados'),
('Metalizados');

-- METODO_PAGO
INSERT INTO METODOS_PAGO (nombre) VALUES
('Transferencia'),
('Yape'),
('Plin');

-- COLORES
INSERT INTO COLORES (nombre) VALUES
('Blanco'),
('Camel'),
('Marrón'),
('Piel'),
('Celeste'),
('Crema'),
('Beige'),
('Negro'),
('Amarillo'),
('Plata'),
('Azul'),
('Rosado'),
('Gris'),
('Rojo'),
('Turquesa'),
('Acero'),
('Verde');

-- TALLAS
INSERT INTO TALLAS (numero) VALUES
(35),
(36),
(37),
(38),
(39);

-- TIPO_BENEFICIO
INSERT INTO TIPOS_BENEFICIO (nombre) VALUES
('Descuento por porcentaje'),
('Descuento fijo'),
('Envío gratis');

-- TIPO_CONDICION
INSERT INTO TIPOS_CONDICION (nombre) VALUES
('Cantidad mínima de productos'),
('Monto mínimo de compra');

-- TIPO_COMPROBANTES
INSERT INTO TIPOS_COMPROBANTE (nombre) VALUES
('Boleta simple'),
('Boleta con DNI'),
('Factura');

-- TIPO_MOVIMIENTO
INSERT INTO TIPOS_MOVIMIENTO (nombre) VALUES
('Ingreso'),
('Salida'),
('Ajuste');
