-- -----------------------------------------------------
-- Database KAWKI_DB
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'KAWKI_DB')
BEGIN
    CREATE DATABASE KAWKI_DB;
END
GO

USE KAWKI_DB;
GO

-- -----------------------------------------------------
-- Table CATEGORIAS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CATEGORIAS')
BEGIN
    CREATE TABLE CATEGORIAS (
        CATEGORIA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(50) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table TIPOS_COMPROBANTE
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TIPOS_COMPROBANTE')
BEGIN
    CREATE TABLE TIPOS_COMPROBANTE (
        TIPO_COMPROBANTE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(45) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table TIPOS_USUARIO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TIPOS_USUARIO')
BEGIN
    CREATE TABLE TIPOS_USUARIO (
        TIPO_USUARIO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(50) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table USUARIOS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USUARIOS')
BEGIN
    CREATE TABLE USUARIOS (
        USUARIO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(50) NOT NULL,
        APE_PATERNO NVARCHAR(50) NOT NULL,
        DNI NVARCHAR(15) NOT NULL,
        TELEFONO NVARCHAR(9) NOT NULL,
        CORREO NVARCHAR(100) NOT NULL,
        NOMBRE_USUARIO NVARCHAR(50) NOT NULL,
        CONTRASENHA NVARCHAR(255) NOT NULL,
        FECHA_HORA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
        TIPO_USUARIO_ID INT NOT NULL,
        ACTIVO BIT NOT NULL,
        CONSTRAINT FK_USUARIOS_TIPOS_USUARIO FOREIGN KEY (TIPO_USUARIO_ID)
            REFERENCES TIPOS_USUARIO(TIPO_USUARIO_ID)
    );
    
    CREATE INDEX IDX_USUARIOS_TIPO_USUARIO ON USUARIOS(TIPO_USUARIO_ID);
END
GO

-- -----------------------------------------------------
-- Table TIPOS_CONDICION
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TIPOS_CONDICION')
BEGIN
    CREATE TABLE TIPOS_CONDICION (
        TIPO_CONDICION_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(45) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table TIPOS_BENEFICIO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TIPOS_BENEFICIO')
BEGIN
    CREATE TABLE TIPOS_BENEFICIO (
        TIPO_BENEFICIO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(45) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table DESCUENTOS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DESCUENTOS')
BEGIN
    CREATE TABLE DESCUENTOS (
        DESCUENTO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DESCRIPCION NVARCHAR(255) NOT NULL,
        TIPO_CONDICION_ID INT NOT NULL,
        VALOR_CONDICION INT NOT NULL,
        TIPO_BENEFICIO_ID INT NOT NULL,
        VALOR_BENEFICIO INT NOT NULL,
        FECHA_INICIO DATETIME NOT NULL,
        FECHA_FIN DATETIME NOT NULL,
        ACTIVO BIT NOT NULL,
        CONSTRAINT FK_DESCUENTOS_TIPOS_CONDICION FOREIGN KEY (TIPO_CONDICION_ID)
            REFERENCES TIPOS_CONDICION(TIPO_CONDICION_ID),
        CONSTRAINT FK_DESCUENTOS_TIPOS_BENEFICIO FOREIGN KEY (TIPO_BENEFICIO_ID)
            REFERENCES TIPOS_BENEFICIO(TIPO_BENEFICIO_ID)
    );
    
    CREATE INDEX IDX_DESCUENTOS_TIPO_CONDICION ON DESCUENTOS(TIPO_CONDICION_ID);
    CREATE INDEX IDX_DESCUENTOS_TIPO_BENEFICIO ON DESCUENTOS(TIPO_BENEFICIO_ID);
END
GO

-- -----------------------------------------------------
-- Table REDES_SOCIALES
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'REDES_SOCIALES')
BEGIN
    CREATE TABLE REDES_SOCIALES (
        RED_SOCIAL_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(25) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table VENTAS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENTAS')
BEGIN
    CREATE TABLE VENTAS (
        VENTA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USUARIO_ID INT NOT NULL,
        FECHA_HORA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
        TOTAL DECIMAL(10,2) NOT NULL,
        DESCUENTO_ID INT NULL,
        RED_SOCIAL_ID INT NOT NULL,
        ES_VALIDA BIT NOT NULL,
        CONSTRAINT FK_VENTAS_USUARIOS FOREIGN KEY (USUARIO_ID)
            REFERENCES USUARIOS(USUARIO_ID),
        CONSTRAINT FK_VENTAS_DESCUENTOS FOREIGN KEY (DESCUENTO_ID)
            REFERENCES DESCUENTOS(DESCUENTO_ID),
        CONSTRAINT FK_VENTAS_REDES_SOCIALES FOREIGN KEY (RED_SOCIAL_ID)
            REFERENCES REDES_SOCIALES(RED_SOCIAL_ID)
    );
    
    CREATE INDEX IDX_VENTAS_USUARIO ON VENTAS(USUARIO_ID);
    CREATE INDEX IDX_VENTAS_DESCUENTO ON VENTAS(DESCUENTO_ID);
    CREATE INDEX IDX_VENTAS_RED_SOCIAL ON VENTAS(RED_SOCIAL_ID);
END
GO

-- -----------------------------------------------------
-- Table METODOS_PAGO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'METODOS_PAGO')
BEGIN
    CREATE TABLE METODOS_PAGO (
        METODO_PAGO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(30) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table COMPROBANTES_PAGO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'COMPROBANTES_PAGO')
BEGIN
    CREATE TABLE COMPROBANTES_PAGO (
        COMPROBANTE_PAGO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        FECHA_HORA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
        TIPO_COMPROBANTE_ID INT NOT NULL,
        NUMERO_SERIE NVARCHAR(50) NOT NULL UNIQUE,
        DNI_CLIENTE NVARCHAR(8) NULL,
        NOMBRE_CLIENTE NVARCHAR(100) NULL,
        RUC_CLIENTE NVARCHAR(11) NULL,
        RAZON_SOCIAL_CLIENTE NVARCHAR(100) NULL,
        DIRECCION_FISCAL_CLIENTE NVARCHAR(200) NULL,
        TELEFONO_CLIENTE NVARCHAR(9) NULL,
        TOTAL DECIMAL(10,2) NOT NULL,
        VENTA_ID INT NOT NULL,
        METODO_PAGO_ID INT NOT NULL,
        SUBTOTAL DECIMAL(10,2) NOT NULL,
        IGV DECIMAL(10,2) NOT NULL,
        CONSTRAINT FK_COMPROBANTES_PAGO_TIPOS_COMPROBANTE FOREIGN KEY (TIPO_COMPROBANTE_ID)
            REFERENCES TIPOS_COMPROBANTE(TIPO_COMPROBANTE_ID),
        CONSTRAINT FK_COMPROBANTES_PAGO_VENTAS FOREIGN KEY (VENTA_ID)
            REFERENCES VENTAS(VENTA_ID),
        CONSTRAINT FK_COMPROBANTES_PAGO_METODOS_PAGO FOREIGN KEY (METODO_PAGO_ID)
            REFERENCES METODOS_PAGO(METODO_PAGO_ID)
    );
    
    CREATE INDEX IDX_COMPROBANTES_TIPO ON COMPROBANTES_PAGO(TIPO_COMPROBANTE_ID);
    CREATE INDEX IDX_COMPROBANTES_VENTA ON COMPROBANTES_PAGO(VENTA_ID);
    CREATE INDEX IDX_COMPROBANTES_METODO_PAGO ON COMPROBANTES_PAGO(METODO_PAGO_ID);
END
GO

-- -----------------------------------------------------
-- Table ESTILOS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ESTILOS')
BEGIN
    CREATE TABLE ESTILOS (
        ESTILO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(30) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table PRODUCTOS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCTOS')
BEGIN
    CREATE TABLE PRODUCTOS (
        PRODUCTO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DESCRIPCION NVARCHAR(100) NOT NULL,
        CATEGORIA_ID INT NOT NULL,
        ESTILO_ID INT NOT NULL,
        PRECIO_VENTA DECIMAL(10,2) NOT NULL,
        FECHA_HORA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
        USUARIO_ID INT NOT NULL,
        CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (CATEGORIA_ID)
            REFERENCES CATEGORIAS(CATEGORIA_ID),
        CONSTRAINT FK_PRODUCTOS_ESTILOS FOREIGN KEY (ESTILO_ID)
            REFERENCES ESTILOS(ESTILO_ID),
        CONSTRAINT FK_PRODUCTOS_USUARIOS FOREIGN KEY (USUARIO_ID)
            REFERENCES USUARIOS(USUARIO_ID)
    );
    
    CREATE INDEX IDX_PRODUCTOS_CATEGORIA ON PRODUCTOS(CATEGORIA_ID);
    CREATE INDEX IDX_PRODUCTOS_ESTILO ON PRODUCTOS(ESTILO_ID);
    CREATE INDEX IDX_PRODUCTOS_USUARIO ON PRODUCTOS(USUARIO_ID);
END
GO

-- -----------------------------------------------------
-- Table COLORES
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'COLORES')
BEGIN
    CREATE TABLE COLORES (
        COLOR_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(30) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table TALLAS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TALLAS')
BEGIN
    CREATE TABLE TALLAS (
        TALLA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NUMERO INT NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table PRODUCTOS_VARIANTES
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCTOS_VARIANTES')
BEGIN
    CREATE TABLE PRODUCTOS_VARIANTES (
        PROD_VARIANTE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        SKU NVARCHAR(45) NOT NULL UNIQUE,
        STOCK INT NOT NULL,
        STOCK_MINIMO INT NOT NULL,
        ALERTA_STOCK BIT NULL,
        PRODUCTO_ID INT NOT NULL,
        COLOR_ID INT NOT NULL,
        TALLA_ID INT NOT NULL,
        URL_IMAGEN NVARCHAR(300) NULL,
        FECHA_HORA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
        DISPONIBLE BIT NOT NULL,
        USUARIO_ID INT NOT NULL,
        CONSTRAINT FK_PRODUCTOS_VARIANTES_PRODUCTOS FOREIGN KEY (PRODUCTO_ID)
            REFERENCES PRODUCTOS(PRODUCTO_ID),
        CONSTRAINT FK_PRODUCTOS_VARIANTES_COLORES FOREIGN KEY (COLOR_ID)
            REFERENCES COLORES(COLOR_ID),
        CONSTRAINT FK_PRODUCTOS_VARIANTES_TALLAS FOREIGN KEY (TALLA_ID)
            REFERENCES TALLAS(TALLA_ID),
        CONSTRAINT FK_PRODUCTOS_VARIANTES_USUARIOS FOREIGN KEY (USUARIO_ID)
            REFERENCES USUARIOS(USUARIO_ID)
    );
    
    CREATE INDEX IDX_PRODUCTOS_VARIANTES_PRODUCTO ON PRODUCTOS_VARIANTES(PRODUCTO_ID);
    CREATE INDEX IDX_PRODUCTOS_VARIANTES_COLOR ON PRODUCTOS_VARIANTES(COLOR_ID);
    CREATE INDEX IDX_PRODUCTOS_VARIANTES_TALLA ON PRODUCTOS_VARIANTES(TALLA_ID);
    CREATE INDEX IDX_PRODUCTOS_VARIANTES_USUARIO ON PRODUCTOS_VARIANTES(USUARIO_ID);
END
GO

-- -----------------------------------------------------
-- Table DETALLE_VENTAS
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DETALLE_VENTAS')
BEGIN
    CREATE TABLE DETALLE_VENTAS (
        DETALLE_VENTA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CANTIDAD INT NOT NULL,
        PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
        SUBTOTAL DECIMAL(10,2) NOT NULL,
        VENTA_ID INT NOT NULL,
        PROD_VARIANTE_ID INT NOT NULL,
        CONSTRAINT FK_DETALLE_VENTAS_VENTAS FOREIGN KEY (VENTA_ID)
            REFERENCES VENTAS(VENTA_ID),
        CONSTRAINT FK_DETALLE_VENTAS_PRODUCTOS_VARIANTES FOREIGN KEY (PROD_VARIANTE_ID)
            REFERENCES PRODUCTOS_VARIANTES(PROD_VARIANTE_ID)
    );
    
    CREATE INDEX IDX_DETALLE_VENTAS_VENTA ON DETALLE_VENTAS(VENTA_ID);
    CREATE INDEX IDX_DETALLE_VENTAS_PROD_VARIANTE ON DETALLE_VENTAS(PROD_VARIANTE_ID);
END
GO

-- -----------------------------------------------------
-- Table TIPOS_MOVIMIENTO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TIPOS_MOVIMIENTO')
BEGIN
    CREATE TABLE TIPOS_MOVIMIENTO (
        TIPO_MOVIMIENTO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOMBRE NVARCHAR(20) NOT NULL
    );
END
GO

-- -----------------------------------------------------
-- Table MOVIMIENTOS_INVENTARIO
-- -----------------------------------------------------
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MOVIMIENTOS_INVENTARIO')
BEGIN
    CREATE TABLE MOVIMIENTOS_INVENTARIO (
        MOV_INVENTARIO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CANTIDAD INT NOT NULL,
        FECHA_HORA_MOV DATETIME NOT NULL,
        OBSERVACION NVARCHAR(200) NULL,
        TIPO_MOVIMIENTO_ID INT NOT NULL,
        PROD_VARIANTE_ID INT NOT NULL,
        USUARIO_ID INT NOT NULL,
        CONSTRAINT FK_MOV_INVENTARIO_TIPOS_MOVIMIENTO FOREIGN KEY (TIPO_MOVIMIENTO_ID)
            REFERENCES TIPOS_MOVIMIENTO(TIPO_MOVIMIENTO_ID),
        CONSTRAINT FK_MOVIMIENTOS_INVENTARIO_PRODUCTOS_VARIANTES FOREIGN KEY (PROD_VARIANTE_ID)
            REFERENCES PRODUCTOS_VARIANTES(PROD_VARIANTE_ID),
        CONSTRAINT FK_MOVIMIENTOS_INVENTARIO_USUARIOS FOREIGN KEY (USUARIO_ID)
            REFERENCES USUARIOS(USUARIO_ID)
    );
    
    CREATE INDEX IDX_MOV_INVENTARIO_TIPO ON MOVIMIENTOS_INVENTARIO(TIPO_MOVIMIENTO_ID);
    CREATE INDEX IDX_MOV_INVENTARIO_PROD_VARIANTE ON MOVIMIENTOS_INVENTARIO(PROD_VARIANTE_ID);
    CREATE INDEX IDX_MOV_INVENTARIO_USUARIO ON MOVIMIENTOS_INVENTARIO(USUARIO_ID);
END
GO

-- =====================================================
-- INSERTS PARA TABLAS MAESTRAS
-- =====================================================

-- TIPO_USUARIO
IF NOT EXISTS (SELECT * FROM TIPOS_USUARIO)
BEGIN
    INSERT INTO TIPOS_USUARIO (NOMBRE) VALUES
    (N'Vendedor'),
    (N'Administrador');
END
GO

-- CATEGORIAS
IF NOT EXISTS (SELECT * FROM CATEGORIAS)
BEGIN
    INSERT INTO CATEGORIAS (NOMBRE) VALUES
    (N'Derby'),
    (N'Oxford');
END
GO

-- ESTILOS
IF NOT EXISTS (SELECT * FROM ESTILOS)
BEGIN
    INSERT INTO ESTILOS (NOMBRE) VALUES
    (N'Charol'),
    (N'Clásicos'),
    (N'Combinados'),
    (N'Metalizados');
END
GO

-- METODO_PAGO
IF NOT EXISTS (SELECT * FROM METODOS_PAGO)
BEGIN
    INSERT INTO METODOS_PAGO (NOMBRE) VALUES
    (N'Transferencia'),
    (N'Yape'),
    (N'Plin');
END
GO

-- COLORES
IF NOT EXISTS (SELECT * FROM COLORES)
BEGIN
    INSERT INTO COLORES (NOMBRE) VALUES
    (N'Blanco'),
    (N'Camel'),
    (N'Marrón'),
    (N'Piel'),
    (N'Celeste'),
    (N'Crema'),
    (N'Beige'),
    (N'Negro'),
    (N'Amarillo'),
    (N'Plata'),
    (N'Azul'),
    (N'Rosado'),
    (N'Gris'),
    (N'Rojo'),
    (N'Turquesa'),
    (N'Acero'),
    (N'Verde');
END
GO

-- TALLAS
IF NOT EXISTS (SELECT * FROM TALLAS)
BEGIN
    INSERT INTO TALLAS (NUMERO) VALUES
    (35),
    (36),
    (37),
    (38),
    (39);
END
GO

-- TIPO_BENEFICIO
IF NOT EXISTS (SELECT * FROM TIPOS_BENEFICIO)
BEGIN
    INSERT INTO TIPOS_BENEFICIO (NOMBRE) VALUES
    (N'Descuento por porcentaje'),
    (N'Descuento fijo'),
    (N'Envío gratis');
END
GO

-- TIPO_CONDICION
IF NOT EXISTS (SELECT * FROM TIPOS_CONDICION)
BEGIN
    INSERT INTO TIPOS_CONDICION (NOMBRE) VALUES
    (N'Cantidad mínima de productos'),
    (N'Monto mínimo de compra');
END
GO

-- TIPO_COMPROBANTES
IF NOT EXISTS (SELECT * FROM TIPOS_COMPROBANTE)
BEGIN
    INSERT INTO TIPOS_COMPROBANTE (NOMBRE) VALUES
    (N'Boleta simple'),
    (N'Boleta con DNI'),
    (N'Factura');
END
GO

-- TIPO_MOVIMIENTO
IF NOT EXISTS (SELECT * FROM TIPOS_MOVIMIENTO)
BEGIN
    INSERT INTO TIPOS_MOVIMIENTO (NOMBRE) VALUES
    (N'Ingreso'),
    (N'Salida'),
    (N'Ajuste');
END
GO

-- REDES_SOCIALES
IF NOT EXISTS (SELECT * FROM REDES_SOCIALES)
BEGIN
    INSERT INTO REDES_SOCIALES (NOMBRE) VALUES
    (N'Facebook'),
    (N'Instagram'),
    (N'WhatsApp');
END
GO

-- USUARIOS
IF NOT EXISTS (SELECT * FROM USUARIOS WHERE DNI = '77045687')
BEGIN
    SET IDENTITY_INSERT USUARIOS ON;
    
    INSERT INTO USUARIOS (
        USUARIO_ID, NOMBRE, APE_PATERNO, DNI, TELEFONO, CORREO, 
        NOMBRE_USUARIO, CONTRASENHA, FECHA_HORA_CREACION, TIPO_USUARIO_ID, ACTIVO
    ) VALUES
    (1, N'Juan', N'Bazán', N'77045687', N'910789123', N'juan@kawki.com', 
     N'juanbaz', N'20216686', GETDATE(), 1, 1),
    (2, N'Helen', N'Castillo', N'74258741', N'986521478', N'helen@kawki.com', 
     N'helencas', N'20202079', GETDATE(), 1, 1),
    (3, N'Fabio', N'Ingaruca', N'75412365', N'985963214', N'fabio@kawki.com', 
     N'fabioing', N'20216590', GETDATE(), 2, 1),
    (4, N'Angelina', N'Fernandez', N'74859632', N'984712365', N'angelina@kawki.com', 
     N'angelinafer', N'20212667', GETDATE(), 2, 1);
    
    SET IDENTITY_INSERT USUARIOS OFF;
END
GO