-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema KAWKI_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KAWKI_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KAWKI_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `KAWKI_DB` ;

-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPO_USUARIO` (
  `TIPO_USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL COMMENT 'Cliente\nVendedor\nAdministrador',
  PRIMARY KEY (`TIPO_USUARIO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`USUARIOS` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APE_PATERNO` VARCHAR(50) NOT NULL,
  `APE_MATERNO` VARCHAR(50) NOT NULL,
  `DNI` VARCHAR(15) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  `DIRECCION` VARCHAR(200) NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  `NOMBRE_USUARIO` VARCHAR(50) NOT NULL,
  `CONTRASENHA` VARCHAR(255) NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TIPO_USUARIO_ID` INT NOT NULL,
  `RUC` VARCHAR(11) NULL,
  `RAZON_SOCIAL` VARCHAR(100) NULL,
  `DIRECCION_FISCAL` VARCHAR(200) NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `FK_USUARIOS_TIPO_USUARIO` (`TIPO_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_USUARIOS_TIPO_USUARIO`
    FOREIGN KEY (`TIPO_USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_USUARIO` (`TIPO_USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPO_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPO_CONDICION` (
  `TIPO_CONDICION_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Cantidad mínima de productos\nMonto mínimo de compra',
  PRIMARY KEY (`TIPO_CONDICION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPO_BENEFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPO_BENEFICIO` (
  `TIPO_BENEFICIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Descuento por porcentaje \nDescuento fijo\nEnvío gratis',
  PRIMARY KEY (`TIPO_BENEFICIO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PROMOCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PROMOCIONES` (
  `PROMOCION_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `TIPO_CONDICION_ID` INT NOT NULL,
  `VALOR_CONDICION` INT NOT NULL COMMENT 'ej. \"3 productos\", \"S/ 200\"',
  `TIPO_BENEFICIO_ID` INT NOT NULL,
  `VALOR_BENEFICIO` INT NOT NULL COMMENT 'ej. \"15%\" o \"S/ 30\"',
  `FECHA_INICIO` DATETIME NOT NULL,
  `FECHA_FIN` DATETIME NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`PROMOCION_ID`),
  INDEX `FK_PROMOCIONES_TIPO_CONDICION` (`TIPO_CONDICION_ID` ASC) VISIBLE,
  INDEX `FK_PROMOCIONES_TIPO_BENEFICIO` (`TIPO_BENEFICIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROMOCIONES_TIPO_CONDICION`
    FOREIGN KEY (`TIPO_CONDICION_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_CONDICION` (`TIPO_CONDICION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROMOCIONES_TIPO_BENEFICIO`
    FOREIGN KEY (`TIPO_BENEFICIO_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_BENEFICIO` (`TIPO_BENEFICIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`CARRITO_COMPRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`CARRITO_COMPRAS` (
  `CARRITO_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `TOTAL` DECIMAL(10,2) NULL,
  `PROMOCION_ID` INT NULL,
  PRIMARY KEY (`CARRITO_ID`),
  INDEX `FK_CARRITO_USUARIO` (`USUARIO_ID` ASC) VISIBLE,
  INDEX `FK_CARRITO_COMPRAS_PROMOCIONES` (`PROMOCION_ID` ASC) VISIBLE,
  CONSTRAINT `FK_CARRITO_USUARIO`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`USUARIOS` (`USUARIO_ID`),
  CONSTRAINT `FK_CARRITO_COMPRAS_PROMOCIONES`
    FOREIGN KEY (`PROMOCION_ID`)
    REFERENCES `KAWKI_DB`.`PROMOCIONES` (`PROMOCION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`CATEGORIAS` (
  `CATEGORIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL COMMENT 'Derby\nOxford',
  PRIMARY KEY (`CATEGORIA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPO_COMPROBANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPO_COMPROBANTES` (
  `TIPO_COMPROBANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Boleta\nFactura',
  PRIMARY KEY (`TIPO_COMPROBANTE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`METODO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`METODO_PAGO` (
  `METODO_PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Tarjeta bancaria\nYape\nPlin',
  PRIMARY KEY (`METODO_PAGO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`ESTADO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`ESTADO_PEDIDO` (
  `ESTADO_PEDIDO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Pendiente\nPagado\nPreparacion\nListo para entregar\nEntregado\nAnulado\n',
  PRIMARY KEY (`ESTADO_PEDIDO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PEDIDOS` (
  `PEDIDO_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TOTAL` DECIMAL(10,2) NOT NULL,
  `ESTADO_PEDIDO_ID` INT NOT NULL,
  `FECHA_HORA_ULTIMO_ESTADO` DATETIME NOT NULL,
  `PROMOCION_ID` INT NULL,
  PRIMARY KEY (`PEDIDO_ID`),
  INDEX `FK_PEDIDOS_USUARIOS` (`USUARIO_ID` ASC) VISIBLE,
  INDEX `FK_PEDIDOS_ESTADO_PEDIDO` (`ESTADO_PEDIDO_ID` ASC) VISIBLE,
  INDEX `FK_PEDIDOS_PROMOCIONES` (`PROMOCION_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PEDIDOS_USUARIOS`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `KAWKI_DB`.`USUARIOS` (`USUARIO_ID`),
  CONSTRAINT `FK_PEDIDOS_ESTADO_PEDIDO`
    FOREIGN KEY (`ESTADO_PEDIDO_ID`)
    REFERENCES `KAWKI_DB`.`ESTADO_PEDIDO` (`ESTADO_PEDIDO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PEDIDOS_PROMOCIONES`
    FOREIGN KEY (`PROMOCION_ID`)
    REFERENCES `KAWKI_DB`.`PROMOCIONES` (`PROMOCION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PAGOS` (
  `PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `MONTO_TOTAL` DECIMAL(10,2) NOT NULL,
  `FECHA_HORA_PAGO` DATETIME NOT NULL,
  `METODO_PAGO_ID` INT NOT NULL,
  `PEDIDO_ID` INT NOT NULL,
  PRIMARY KEY (`PAGO_ID`),
  INDEX `FK_PAGOS_METODO_PAGO` (`METODO_PAGO_ID` ASC) VISIBLE,
  INDEX `FK_PAGOS_PEDIDOS` (`PEDIDO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PAGOS_METODO_PAGO`
    FOREIGN KEY (`METODO_PAGO_ID`)
    REFERENCES `KAWKI_DB`.`METODO_PAGO` (`METODO_PAGO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PAGOS_PEDIDOS`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `KAWKI_DB`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`COMPROBANTE_PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`COMPROBANTE_PAGOS` (
  `COMPROBANTE_PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `PAGO_ID` INT NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TIPO_COMPROBANTE_ID` INT NOT NULL,
  `NUMERO_SERIE` VARCHAR(50) NOT NULL,
  `DNI_CLIENTE` VARCHAR(8) NULL,
  `NOMBRE_CLIENTE` VARCHAR(100) NULL,
  `RUC_CLIENTE` VARCHAR(11) NULL,
  `RAZON_SOCIAL_CLIENTE` VARCHAR(100) NULL,
  `DIRECCION_FISCAL_CLIENTE` VARCHAR(200) NULL,
  `CORREO_CLIENTE` VARCHAR(80) NOT NULL,
  `TELEFONO_CLIENTE` VARCHAR(9) NOT NULL,
  `TOTAL` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`COMPROBANTE_PAGO_ID`),
  UNIQUE INDEX `NUMERO_SERIE` (`NUMERO_SERIE` ASC) VISIBLE,
  INDEX `FK_COMPROBANTE_PAGOS_TIPO_COMPROBANTES` (`TIPO_COMPROBANTE_ID` ASC) VISIBLE,
  INDEX `FK_COMPROBANTE_PAGOS_PAGOS` (`PAGO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_COMPROBANTE_PAGOS_TIPO_COMPROBANTES`
    FOREIGN KEY (`TIPO_COMPROBANTE_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_COMPROBANTES` (`TIPO_COMPROBANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPROBANTE_PAGOS_PAGOS`
    FOREIGN KEY (`PAGO_ID`)
    REFERENCES `KAWKI_DB`.`PAGOS` (`PAGO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`ESTILOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`ESTILOS` (
  `ESTILO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Charol\nClásicos\nCombinados\nMetalizados',
  PRIMARY KEY (`ESTILO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PRODUCTOS` (
  `PRODUCTO_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  `CATEGORIA_ID` INT NOT NULL,
  `ESTILO_ID` INT NOT NULL,
  `PRECIO_VENTA` DECIMAL(10,2) NOT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCTO_ID`),
  INDEX `FK_PRODUCTOS_CATEGORIAS` (`CATEGORIA_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_ESTILOS` (`ESTILO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTOS_CATEGORIAS`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `KAWKI_DB`.`CATEGORIAS` (`CATEGORIA_ID`),
  CONSTRAINT `FK_PRODUCTOS_ESTILOS`
    FOREIGN KEY (`ESTILO_ID`)
    REFERENCES `KAWKI_DB`.`ESTILOS` (`ESTILO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`COLORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`COLORES` (
  `COLOR_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL COMMENT 'Blanco \nCamel \nMarrón \nPiel \nCeleste \nCrema \nBeige \nNegro \nAmarillo \nPlata \nAzul \nRosado \nGris \nRojo \nTurquesa \nAcero \nVerde \n',
  PRIMARY KEY (`COLOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TALLAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TALLAS` (
  `TALLA_ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL COMMENT '35\n36\n37\n38\n39',
  PRIMARY KEY (`TALLA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`PRODUCTOS_VARIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`PRODUCTOS_VARIANTES` (
  `PROD_VARIANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `SKU` VARCHAR(45) NOT NULL,
  `STOCK` INT NOT NULL,
  `STOCK_MINIMO` INT NOT NULL,
  `ALERTA_STOCK` TINYINT(1) NULL,
  `PRODUCTO_ID` INT NOT NULL,
  `COLOR_ID` INT NOT NULL,
  `TALLA_ID` INT NOT NULL,
  `TIPO_BENEFICIO_ID` INT NULL,
  `VALOR_BENEFICIO` INT NULL,
  `FECHA_HORA_CREACION` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROD_VARIANTE_ID`),
  INDEX `FK_PRODUCTOS_VARIANTES_PRODUCTOS` (`PRODUCTO_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_VARIANTES_COLORES` (`COLOR_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_VARIANTES_TALLAS` (`TALLA_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCTOS_VARIANTES_TIPO_BENEFICIO` (`TIPO_BENEFICIO_ID` ASC) VISIBLE,
  UNIQUE INDEX `SKU_UNIQUE` (`SKU` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_PRODUCTOS`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS` (`PRODUCTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_COLORES`
    FOREIGN KEY (`COLOR_ID`)
    REFERENCES `KAWKI_DB`.`COLORES` (`COLOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_TALLAS`
    FOREIGN KEY (`TALLA_ID`)
    REFERENCES `KAWKI_DB`.`TALLAS` (`TALLA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTOS_VARIANTES_TIPO_BENEFICIO`
    FOREIGN KEY (`TIPO_BENEFICIO_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_BENEFICIO` (`TIPO_BENEFICIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`DETALLE_CARRITOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`DETALLE_CARRITOS` (
  `DETALLE_CARRITO_ID` INT NOT NULL AUTO_INCREMENT,
  `CARRITO_ID` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNITARIO` DECIMAL(10,2) NOT NULL,
  `SUBTOTAL` DECIMAL(10,2) NOT NULL,
  `PROD_VARIANTE_ID` INT NOT NULL,
  PRIMARY KEY (`DETALLE_CARRITO_ID`),
  INDEX `FK_DETALLE_CARRITOS_CARRITO_COMPRAS` (`CARRITO_ID` ASC) VISIBLE,
  INDEX `_DETALLE_CARRITOS_PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_CARRITOS_CARRITO_COMPRAS`
    FOREIGN KEY (`CARRITO_ID`)
    REFERENCES `KAWKI_DB`.`CARRITO_COMPRAS` (`CARRITO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DETALLE_CARRITOS_PRODUCTOS_VARIANTES`
    FOREIGN KEY (`PROD_VARIANTE_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`DETALLE_PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`DETALLE_PEDIDOS` (
  `DETALLE_PEDIDO_ID` INT NOT NULL AUTO_INCREMENT,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNITARIO` DECIMAL(10,2) NOT NULL,
  `SUBTOTAL` DECIMAL(10,2) NOT NULL,
  `PEDIDO_ID` INT NOT NULL,
  `PROD_VARIANTE_ID` INT NOT NULL,
  PRIMARY KEY (`DETALLE_PEDIDO_ID`),
  INDEX `FK_DETALLE_PEDIDOS_PEDIDOS` (`PEDIDO_ID` ASC) VISIBLE,
  INDEX `FK_DETALLE_PEDIDOS_PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_PEDIDOS_PEDIDOS`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `KAWKI_DB`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DETALLE_PEDIDOS_PRODUCTOS_VARIANTES`
    FOREIGN KEY (`PROD_VARIANTE_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`COURIERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`COURIERS` (
  `COURIER_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Shalom\nOlva Courier\nUrbano',
  PRIMARY KEY (`COURIER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`ESTADO_ENVIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`ESTADO_ENVIO` (
  `ESTADO_ENVIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL COMMENT 'Pendiente\nProgramado\nEncargado al courier\nDisponible en almacen\nEntregado\nAnulador\n',
  PRIMARY KEY (`ESTADO_ENVIO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`ENVIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`ENVIOS` (
  `ENVIO_ID` INT NOT NULL AUTO_INCREMENT,
  `ES_DELIVERY` TINYINT(1) NOT NULL,
  `DIRECCION_ENTREGA` VARCHAR(255) NOT NULL DEFAULT 'Almacén Kawki',
  `COURIER_ID` INT NULL,
  `FECHA_ENVIO` DATETIME NULL COMMENT 'Es la fecha en la cual se dejó entregado el producto al courier',
  `COSTO_ENVIO` DECIMAL(10,2) NULL,
  `PEDIDO_ID` INT NOT NULL,
  `ESTADO_ENVIO_ID` INT NOT NULL,
  `FECHA_ULTIMO_ESTADO` DATETIME NOT NULL,
  PRIMARY KEY (`ENVIO_ID`),
  INDEX `FK_ENVIOS_COURIER` (`COURIER_ID` ASC) VISIBLE,
  INDEX `FK_ENVIOS_PEDIDOS` (`PEDIDO_ID` ASC) VISIBLE,
  INDEX `FK_ENVIOS_ESTADO_ENVO` (`ESTADO_ENVIO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ENVIOS_COURIER`
    FOREIGN KEY (`COURIER_ID`)
    REFERENCES `KAWKI_DB`.`COURIERS` (`COURIER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENVIOS_PEDIDOS`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `KAWKI_DB`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENVIOS_ESTADO_ENVO`
    FOREIGN KEY (`ESTADO_ENVIO_ID`)
    REFERENCES `KAWKI_DB`.`ESTADO_ENVIO` (`ESTADO_ENVIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`TIPO_MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`TIPO_MOVIMIENTO` (
  `TIPO_MOVIMIENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NOT NULL COMMENT 'Ingreso\nSalida\nAjuste',
  PRIMARY KEY (`TIPO_MOVIMIENTO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KAWKI_DB`.`MOVIMIENTOS_INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAWKI_DB`.`MOVIMIENTOS_INVENTARIO` (
  `MOV_INVENTARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `CANTIDAD` INT NOT NULL,
  `FECHA_HORA_MOV` DATETIME NOT NULL,
  `OBSERVACION` VARCHAR(200) NULL,
  `TIPO_MOVIMIENTO_ID` INT NOT NULL,
  `PROD_VARIANTE_ID` INT NOT NULL,
  PRIMARY KEY (`MOV_INVENTARIO_ID`),
  INDEX `FK_MOV_INVENTARIO_TIPO_MOVIMIENTO` (`TIPO_MOVIMIENTO_ID` ASC) VISIBLE,
  INDEX `FK_MOVIMIENTOS_INVENTARIO_PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_MOV_INVENTARIO_TIPO_MOVIMIENTO`
    FOREIGN KEY (`TIPO_MOVIMIENTO_ID`)
    REFERENCES `KAWKI_DB`.`TIPO_MOVIMIENTO` (`TIPO_MOVIMIENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MOVIMIENTOS_INVENTARIO_PRODUCTOS_VARIANTES`
    FOREIGN KEY (`PROD_VARIANTE_ID`)
    REFERENCES `KAWKI_DB`.`PRODUCTOS_VARIANTES` (`PROD_VARIANTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- INSERTS PARA TABLAS MAESTRAS

-- TIPO_USUARIO
INSERT INTO TIPO_USUARIO (nombre) VALUES
('Cliente'),
('Vendedor'),
('Administrador');

-- CATEGORIAS
INSERT INTO CATEGORIAS (nombre) VALUES
('Derby'),
('Oxford');

-- ESTILOS
INSERT INTO ESTILOS (nombre) VALUES
('Charol'),
('Clásicos'),
('Combinados'),
('Metalizados');

-- ESTADO_ENVIO
INSERT INTO ESTADO_ENVIO (nombre) VALUES
('Pendiente'),
('Programado'),
('Encargado al courier'),
('Disponible en almacen'),
('Entregado'),
('Anulado');

-- COURIERS
INSERT INTO COURIERS (nombre) VALUES
('Shalom'),
('Olva Courier'),
('Urbano');

-- ESTADO_PEDIDO
INSERT INTO ESTADO_PEDIDO (nombre) VALUES
('Pendiente'),
('Pagado'),
('Preparacion'),
('Listo para entregar'),
('Entregado'),
('Anulado');

-- METODO_PAGO
INSERT INTO METODO_PAGO (nombre) VALUES
('Tarjeta bancaria'),
('Yape'),
('Plin');

-- COLORES
INSERT INTO COLORES (nombre) VALUES
('Blanco'),
('Camel'),
('Marrón'),
('Piel'),
('Celeste'),
('Crema'),
('Beige'),
('Negro'),
('Amarillo'),
('Plata'),
('Azul'),
('Rosado'),
('Gris'),
('Rojo'),
('Turquesa'),
('Acero'),
('Verde');

-- TALLAS
INSERT INTO TALLAS (numero) VALUES
(35),
(36),
(37),
(38),
(39);

-- TIPO_BENEFICIO
INSERT INTO TIPO_BENEFICIO (nombre) VALUES
('Descuento por porcentaje'),
('Descuento fijo'),
('Envío gratis');

-- TIPO_CONDICION
INSERT INTO TIPO_CONDICION (nombre) VALUES
('Cantidad mínima de productos'),
('Monto mínimo de compra');

-- TIPO_COMPROBANTES
INSERT INTO TIPO_COMPROBANTES (nombre) VALUES
('Boleta'),
('Factura');

-- TIPO_MOVIMIENTO
INSERT INTO TIPO_MOVIMIENTO (nombre) VALUES
('Ingreso'),
('Salida'),
('Ajuste');
