//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSRedesSociales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSRedesSociales.RedesSociales")]
    public interface RedesSociales {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/listarTodosRedSocia" +
            "lRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/listarTodosRedSocia" +
            "lResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse listarTodosRedSocial(KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/listarTodosRedSocia" +
            "lRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/listarTodosRedSocia" +
            "lResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse> listarTodosRedSocialAsync(KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/obtenerPorIdRedSoci" +
            "alRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/obtenerPorIdRedSoci" +
            "alResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse obtenerPorIdRedSocial(KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/obtenerPorIdRedSoci" +
            "alRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/RedesSociales/obtenerPorIdRedSoci" +
            "alResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse> obtenerPorIdRedSocialAsync(KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class redesSocialesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int redSocialIdField;
        
        private bool redSocialIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int redSocialId {
            get {
                return this.redSocialIdField;
            }
            set {
                this.redSocialIdField = value;
                this.RaisePropertyChanged("redSocialId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool redSocialIdSpecified {
            get {
                return this.redSocialIdFieldSpecified;
            }
            set {
                this.redSocialIdFieldSpecified = value;
                this.RaisePropertyChanged("redSocialIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRedSocial", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRedSocialRequest {
        
        public listarTodosRedSocialRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRedSocialResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRedSocialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO[] @return;
        
        public listarTodosRedSocialResponse() {
        }
        
        public listarTodosRedSocialResponse(KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdRedSocial", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRedSocialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int redSocialId;
        
        public obtenerPorIdRedSocialRequest() {
        }
        
        public obtenerPorIdRedSocialRequest(int redSocialId) {
            this.redSocialId = redSocialId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdRedSocialResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRedSocialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO @return;
        
        public obtenerPorIdRedSocialResponse() {
        }
        
        public obtenerPorIdRedSocialResponse(KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RedesSocialesChannel : KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RedesSocialesClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales>, KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales {
        
        public RedesSocialesClient() {
        }
        
        public RedesSocialesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RedesSocialesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RedesSocialesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RedesSocialesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales.listarTodosRedSocial(KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest request) {
            return base.Channel.listarTodosRedSocial(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO[] listarTodosRedSocial() {
            KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest inValue = new KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest();
            KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse retVal = ((KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales)(this)).listarTodosRedSocial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse> KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales.listarTodosRedSocialAsync(KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest request) {
            return base.Channel.listarTodosRedSocialAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialResponse> listarTodosRedSocialAsync() {
            KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest inValue = new KawkiWebBusiness.KawkiWebWSRedesSociales.listarTodosRedSocialRequest();
            return ((KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales)(this)).listarTodosRedSocialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales.obtenerPorIdRedSocial(KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest request) {
            return base.Channel.obtenerPorIdRedSocial(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSRedesSociales.redesSocialesDTO obtenerPorIdRedSocial(int redSocialId) {
            KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest inValue = new KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest();
            inValue.redSocialId = redSocialId;
            KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse retVal = ((KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales)(this)).obtenerPorIdRedSocial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse> KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales.obtenerPorIdRedSocialAsync(KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest request) {
            return base.Channel.obtenerPorIdRedSocialAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialResponse> obtenerPorIdRedSocialAsync(int redSocialId) {
            KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest inValue = new KawkiWebBusiness.KawkiWebWSRedesSociales.obtenerPorIdRedSocialRequest();
            inValue.redSocialId = redSocialId;
            return ((KawkiWebBusiness.KawkiWebWSRedesSociales.RedesSociales)(this)).obtenerPorIdRedSocialAsync(inValue);
        }
    }
}
