//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSEstilos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSEstilos.Estilos")]
    public interface Estilos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/modificarEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/modificarEstiloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse modificarEstilo(KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/modificarEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/modificarEstiloResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse> modificarEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/insertarEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/insertarEstiloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse insertarEstilo(KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/insertarEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/insertarEstiloResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse> insertarEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/obtenerPorIdEstiloRequest" +
            "", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/obtenerPorIdEstiloRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse obtenerPorIdEstilo(KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/obtenerPorIdEstiloRequest" +
            "", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/obtenerPorIdEstiloRespons" +
            "e")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse> obtenerPorIdEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/listarTodosEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/listarTodosEstiloResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse listarTodosEstilo(KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/listarTodosEstiloRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Estilos/listarTodosEstiloResponse" +
            "")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse> listarTodosEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEstilo", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEstiloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estiloId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreEstilo;
        
        public modificarEstiloRequest() {
        }
        
        public modificarEstiloRequest(int estiloId, string nombreEstilo) {
            this.estiloId = estiloId;
            this.nombreEstilo = nombreEstilo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEstiloResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEstiloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEstiloResponse() {
        }
        
        public modificarEstiloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstilo", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEstiloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreEstilo;
        
        public insertarEstiloRequest() {
        }
        
        public insertarEstiloRequest(string nombreEstilo) {
            this.nombreEstilo = nombreEstilo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstiloResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEstiloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEstiloResponse() {
        }
        
        public insertarEstiloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class estilosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estilo_idField;
        
        private bool estilo_idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estilo_id {
            get {
                return this.estilo_idField;
            }
            set {
                this.estilo_idField = value;
                this.RaisePropertyChanged("estilo_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estilo_idSpecified {
            get {
                return this.estilo_idFieldSpecified;
            }
            set {
                this.estilo_idFieldSpecified = value;
                this.RaisePropertyChanged("estilo_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdEstilo", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdEstiloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estiloId;
        
        public obtenerPorIdEstiloRequest() {
        }
        
        public obtenerPorIdEstiloRequest(int estiloId) {
            this.estiloId = estiloId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdEstiloResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdEstiloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO @return;
        
        public obtenerPorIdEstiloResponse() {
        }
        
        public obtenerPorIdEstiloResponse(KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEstilo", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEstiloRequest {
        
        public listarTodosEstiloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEstiloResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEstiloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO[] @return;
        
        public listarTodosEstiloResponse() {
        }
        
        public listarTodosEstiloResponse(KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstilosChannel : KawkiWebBusiness.KawkiWebWSEstilos.Estilos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstilosClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSEstilos.Estilos>, KawkiWebBusiness.KawkiWebWSEstilos.Estilos {
        
        public EstilosClient() {
        }
        
        public EstilosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstilosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstilosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstilosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse KawkiWebBusiness.KawkiWebWSEstilos.Estilos.modificarEstilo(KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest request) {
            return base.Channel.modificarEstilo(request);
        }
        
        public int modificarEstilo(int estiloId, string nombreEstilo) {
            KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest();
            inValue.estiloId = estiloId;
            inValue.nombreEstilo = nombreEstilo;
            KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse retVal = ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).modificarEstilo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse> KawkiWebBusiness.KawkiWebWSEstilos.Estilos.modificarEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest request) {
            return base.Channel.modificarEstiloAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloResponse> modificarEstiloAsync(int estiloId, string nombreEstilo) {
            KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.modificarEstiloRequest();
            inValue.estiloId = estiloId;
            inValue.nombreEstilo = nombreEstilo;
            return ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).modificarEstiloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse KawkiWebBusiness.KawkiWebWSEstilos.Estilos.insertarEstilo(KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest request) {
            return base.Channel.insertarEstilo(request);
        }
        
        public int insertarEstilo(string nombreEstilo) {
            KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest();
            inValue.nombreEstilo = nombreEstilo;
            KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse retVal = ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).insertarEstilo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse> KawkiWebBusiness.KawkiWebWSEstilos.Estilos.insertarEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest request) {
            return base.Channel.insertarEstiloAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloResponse> insertarEstiloAsync(string nombreEstilo) {
            KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.insertarEstiloRequest();
            inValue.nombreEstilo = nombreEstilo;
            return ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).insertarEstiloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse KawkiWebBusiness.KawkiWebWSEstilos.Estilos.obtenerPorIdEstilo(KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest request) {
            return base.Channel.obtenerPorIdEstilo(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO obtenerPorIdEstilo(int estiloId) {
            KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest();
            inValue.estiloId = estiloId;
            KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse retVal = ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).obtenerPorIdEstilo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse> KawkiWebBusiness.KawkiWebWSEstilos.Estilos.obtenerPorIdEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest request) {
            return base.Channel.obtenerPorIdEstiloAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloResponse> obtenerPorIdEstiloAsync(int estiloId) {
            KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.obtenerPorIdEstiloRequest();
            inValue.estiloId = estiloId;
            return ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).obtenerPorIdEstiloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse KawkiWebBusiness.KawkiWebWSEstilos.Estilos.listarTodosEstilo(KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest request) {
            return base.Channel.listarTodosEstilo(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSEstilos.estilosDTO[] listarTodosEstilo() {
            KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest();
            KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse retVal = ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).listarTodosEstilo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse> KawkiWebBusiness.KawkiWebWSEstilos.Estilos.listarTodosEstiloAsync(KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest request) {
            return base.Channel.listarTodosEstiloAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloResponse> listarTodosEstiloAsync() {
            KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest inValue = new KawkiWebBusiness.KawkiWebWSEstilos.listarTodosEstiloRequest();
            return ((KawkiWebBusiness.KawkiWebWSEstilos.Estilos)(this)).listarTodosEstiloAsync(inValue);
        }
    }
}
