//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSMetodosPago {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSMetodosPago.MetodosPago")]
    public interface MetodosPago {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/listarTodosMetodoPago" +
            "Request", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/listarTodosMetodoPago" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse listarTodosMetodoPago(KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/listarTodosMetodoPago" +
            "Request", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/listarTodosMetodoPago" +
            "Response")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse> listarTodosMetodoPagoAsync(KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/obtenerPorIdMetodoPag" +
            "oRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/obtenerPorIdMetodoPag" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse obtenerPorIdMetodoPago(KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/obtenerPorIdMetodoPag" +
            "oRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/MetodosPago/obtenerPorIdMetodoPag" +
            "oResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse> obtenerPorIdMetodoPagoAsync(KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class metodosPagoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int metodo_pago_idField;
        
        private bool metodo_pago_idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int metodo_pago_id {
            get {
                return this.metodo_pago_idField;
            }
            set {
                this.metodo_pago_idField = value;
                this.RaisePropertyChanged("metodo_pago_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodo_pago_idSpecified {
            get {
                return this.metodo_pago_idFieldSpecified;
            }
            set {
                this.metodo_pago_idFieldSpecified = value;
                this.RaisePropertyChanged("metodo_pago_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMetodoPago", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMetodoPagoRequest {
        
        public listarTodosMetodoPagoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMetodoPagoResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMetodoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO[] @return;
        
        public listarTodosMetodoPagoResponse() {
        }
        
        public listarTodosMetodoPagoResponse(KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMetodoPago", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMetodoPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int metodoPagoId;
        
        public obtenerPorIdMetodoPagoRequest() {
        }
        
        public obtenerPorIdMetodoPagoRequest(int metodoPagoId) {
            this.metodoPagoId = metodoPagoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMetodoPagoResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMetodoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO @return;
        
        public obtenerPorIdMetodoPagoResponse() {
        }
        
        public obtenerPorIdMetodoPagoResponse(KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosPagoChannel : KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosPagoClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago>, KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago {
        
        public MetodosPagoClient() {
        }
        
        public MetodosPagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosPagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosPagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosPagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago.listarTodosMetodoPago(KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest request) {
            return base.Channel.listarTodosMetodoPago(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO[] listarTodosMetodoPago() {
            KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest inValue = new KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest();
            KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse retVal = ((KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago)(this)).listarTodosMetodoPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse> KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago.listarTodosMetodoPagoAsync(KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest request) {
            return base.Channel.listarTodosMetodoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoResponse> listarTodosMetodoPagoAsync() {
            KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest inValue = new KawkiWebBusiness.KawkiWebWSMetodosPago.listarTodosMetodoPagoRequest();
            return ((KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago)(this)).listarTodosMetodoPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago.obtenerPorIdMetodoPago(KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest request) {
            return base.Channel.obtenerPorIdMetodoPago(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSMetodosPago.metodosPagoDTO obtenerPorIdMetodoPago(int metodoPagoId) {
            KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest inValue = new KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest();
            inValue.metodoPagoId = metodoPagoId;
            KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse retVal = ((KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago)(this)).obtenerPorIdMetodoPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse> KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago.obtenerPorIdMetodoPagoAsync(KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest request) {
            return base.Channel.obtenerPorIdMetodoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoResponse> obtenerPorIdMetodoPagoAsync(int metodoPagoId) {
            KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest inValue = new KawkiWebBusiness.KawkiWebWSMetodosPago.obtenerPorIdMetodoPagoRequest();
            inValue.metodoPagoId = metodoPagoId;
            return ((KawkiWebBusiness.KawkiWebWSMetodosPago.MetodosPago)(this)).obtenerPorIdMetodoPagoAsync(inValue);
        }
    }
}
