//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSTiposMovimiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSTiposMovimiento.TiposMovimiento")]
    public interface TiposMovimiento {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/obtenerPorIdTipoM" +
            "ovimientoRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/obtenerPorIdTipoM" +
            "ovimientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse obtenerPorIdTipoMovimiento(KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/obtenerPorIdTipoM" +
            "ovimientoRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/obtenerPorIdTipoM" +
            "ovimientoResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse> obtenerPorIdTipoMovimientoAsync(KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/listarTodosTipoMo" +
            "vimientoRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/listarTodosTipoMo" +
            "vimientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse listarTodosTipoMovimiento(KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/listarTodosTipoMo" +
            "vimientoRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposMovimiento/listarTodosTipoMo" +
            "vimientoResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse> listarTodosTipoMovimientoAsync(KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class tiposMovimientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipoMovimientoIdField;
        
        private bool tipoMovimientoIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int tipoMovimientoId {
            get {
                return this.tipoMovimientoIdField;
            }
            set {
                this.tipoMovimientoIdField = value;
                this.RaisePropertyChanged("tipoMovimientoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMovimientoIdSpecified {
            get {
                return this.tipoMovimientoIdFieldSpecified;
            }
            set {
                this.tipoMovimientoIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoMovimientoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoMovimiento", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoMovimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoMovimientoId;
        
        public obtenerPorIdTipoMovimientoRequest() {
        }
        
        public obtenerPorIdTipoMovimientoRequest(int tipoMovimientoId) {
            this.tipoMovimientoId = tipoMovimientoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoMovimientoResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoMovimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO @return;
        
        public obtenerPorIdTipoMovimientoResponse() {
        }
        
        public obtenerPorIdTipoMovimientoResponse(KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoMovimiento", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoMovimientoRequest {
        
        public listarTodosTipoMovimientoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoMovimientoResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoMovimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO[] @return;
        
        public listarTodosTipoMovimientoResponse() {
        }
        
        public listarTodosTipoMovimientoResponse(KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiposMovimientoChannel : KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiposMovimientoClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento>, KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento {
        
        public TiposMovimientoClient() {
        }
        
        public TiposMovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiposMovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposMovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposMovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento.obtenerPorIdTipoMovimiento(KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest request) {
            return base.Channel.obtenerPorIdTipoMovimiento(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO obtenerPorIdTipoMovimiento(int tipoMovimientoId) {
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest();
            inValue.tipoMovimientoId = tipoMovimientoId;
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse retVal = ((KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento)(this)).obtenerPorIdTipoMovimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse> KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento.obtenerPorIdTipoMovimientoAsync(KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest request) {
            return base.Channel.obtenerPorIdTipoMovimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoResponse> obtenerPorIdTipoMovimientoAsync(int tipoMovimientoId) {
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposMovimiento.obtenerPorIdTipoMovimientoRequest();
            inValue.tipoMovimientoId = tipoMovimientoId;
            return ((KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento)(this)).obtenerPorIdTipoMovimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento.listarTodosTipoMovimiento(KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest request) {
            return base.Channel.listarTodosTipoMovimiento(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSTiposMovimiento.tiposMovimientoDTO[] listarTodosTipoMovimiento() {
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest();
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse retVal = ((KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento)(this)).listarTodosTipoMovimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse> KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento.listarTodosTipoMovimientoAsync(KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest request) {
            return base.Channel.listarTodosTipoMovimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoResponse> listarTodosTipoMovimientoAsync() {
            KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposMovimiento.listarTodosTipoMovimientoRequest();
            return ((KawkiWebBusiness.KawkiWebWSTiposMovimiento.TiposMovimiento)(this)).listarTodosTipoMovimientoAsync(inValue);
        }
    }
}
