//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSColores {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSColores.Colores")]
    public interface Colores {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/insertarColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/insertarColorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse insertarColor(KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/insertarColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/insertarColorResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse> insertarColorAsync(KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/obtenerPorIdColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/obtenerPorIdColorResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse obtenerPorIdColor(KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/obtenerPorIdColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/obtenerPorIdColorResponse" +
            "")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse> obtenerPorIdColorAsync(KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/listarTodosColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/listarTodosColorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse listarTodosColor(KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/listarTodosColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/listarTodosColorResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse> listarTodosColorAsync(KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/modificarColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/modificarColorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse modificarColor(KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/modificarColorRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/Colores/modificarColorResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse> modificarColorAsync(KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarColor", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreColor;
        
        public insertarColorRequest() {
        }
        
        public insertarColorRequest(string nombreColor) {
            this.nombreColor = nombreColor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarColorResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarColorResponse() {
        }
        
        public insertarColorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class coloresDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int color_idField;
        
        private bool color_idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int color_id {
            get {
                return this.color_idField;
            }
            set {
                this.color_idField = value;
                this.RaisePropertyChanged("color_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool color_idSpecified {
            get {
                return this.color_idFieldSpecified;
            }
            set {
                this.color_idFieldSpecified = value;
                this.RaisePropertyChanged("color_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdColor", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int colorId;
        
        public obtenerPorIdColorRequest() {
        }
        
        public obtenerPorIdColorRequest(int colorId) {
            this.colorId = colorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdColorResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSColores.coloresDTO @return;
        
        public obtenerPorIdColorResponse() {
        }
        
        public obtenerPorIdColorResponse(KawkiWebBusiness.KawkiWebWSColores.coloresDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosColor", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosColorRequest {
        
        public listarTodosColorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosColorResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSColores.coloresDTO[] @return;
        
        public listarTodosColorResponse() {
        }
        
        public listarTodosColorResponse(KawkiWebBusiness.KawkiWebWSColores.coloresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarColor", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int colorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreColor;
        
        public modificarColorRequest() {
        }
        
        public modificarColorRequest(int colorId, string nombreColor) {
            this.colorId = colorId;
            this.nombreColor = nombreColor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarColorResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarColorResponse() {
        }
        
        public modificarColorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColoresChannel : KawkiWebBusiness.KawkiWebWSColores.Colores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColoresClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSColores.Colores>, KawkiWebBusiness.KawkiWebWSColores.Colores {
        
        public ColoresClient() {
        }
        
        public ColoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse KawkiWebBusiness.KawkiWebWSColores.Colores.insertarColor(KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest request) {
            return base.Channel.insertarColor(request);
        }
        
        public int insertarColor(string nombreColor) {
            KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest();
            inValue.nombreColor = nombreColor;
            KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse retVal = ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).insertarColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse> KawkiWebBusiness.KawkiWebWSColores.Colores.insertarColorAsync(KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest request) {
            return base.Channel.insertarColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.insertarColorResponse> insertarColorAsync(string nombreColor) {
            KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.insertarColorRequest();
            inValue.nombreColor = nombreColor;
            return ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).insertarColorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse KawkiWebBusiness.KawkiWebWSColores.Colores.obtenerPorIdColor(KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest request) {
            return base.Channel.obtenerPorIdColor(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSColores.coloresDTO obtenerPorIdColor(int colorId) {
            KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest();
            inValue.colorId = colorId;
            KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse retVal = ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).obtenerPorIdColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse> KawkiWebBusiness.KawkiWebWSColores.Colores.obtenerPorIdColorAsync(KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest request) {
            return base.Channel.obtenerPorIdColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorResponse> obtenerPorIdColorAsync(int colorId) {
            KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.obtenerPorIdColorRequest();
            inValue.colorId = colorId;
            return ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).obtenerPorIdColorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse KawkiWebBusiness.KawkiWebWSColores.Colores.listarTodosColor(KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest request) {
            return base.Channel.listarTodosColor(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSColores.coloresDTO[] listarTodosColor() {
            KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest();
            KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse retVal = ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).listarTodosColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse> KawkiWebBusiness.KawkiWebWSColores.Colores.listarTodosColorAsync(KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest request) {
            return base.Channel.listarTodosColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.listarTodosColorResponse> listarTodosColorAsync() {
            KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.listarTodosColorRequest();
            return ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).listarTodosColorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse KawkiWebBusiness.KawkiWebWSColores.Colores.modificarColor(KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest request) {
            return base.Channel.modificarColor(request);
        }
        
        public int modificarColor(int colorId, string nombreColor) {
            KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest();
            inValue.colorId = colorId;
            inValue.nombreColor = nombreColor;
            KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse retVal = ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).modificarColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse> KawkiWebBusiness.KawkiWebWSColores.Colores.modificarColorAsync(KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest request) {
            return base.Channel.modificarColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSColores.modificarColorResponse> modificarColorAsync(int colorId, string nombreColor) {
            KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest inValue = new KawkiWebBusiness.KawkiWebWSColores.modificarColorRequest();
            inValue.colorId = colorId;
            inValue.nombreColor = nombreColor;
            return ((KawkiWebBusiness.KawkiWebWSColores.Colores)(this)).modificarColorAsync(inValue);
        }
    }
}
