//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawkiWebBusiness.KawkiWebWSTiposBeneficio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", ConfigurationName="KawkiWebWSTiposBeneficio.TiposBeneficio")]
    public interface TiposBeneficio {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/listarTodosTipoBen" +
            "eficioRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/listarTodosTipoBen" +
            "eficioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse listarTodosTipoBeneficio(KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/listarTodosTipoBen" +
            "eficioRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/listarTodosTipoBen" +
            "eficioResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse> listarTodosTipoBeneficioAsync(KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/obtenerPorIdTipoBe" +
            "neficioRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/obtenerPorIdTipoBe" +
            "neficioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse obtenerPorIdTipoBeneficio(KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/obtenerPorIdTipoBe" +
            "neficioRequest", ReplyAction="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/TiposBeneficio/obtenerPorIdTipoBe" +
            "neficioResponse")]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse> obtenerPorIdTipoBeneficioAsync(KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/")]
    public partial class tiposBeneficioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipo_beneficio_idField;
        
        private bool tipo_beneficio_idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int tipo_beneficio_id {
            get {
                return this.tipo_beneficio_idField;
            }
            set {
                this.tipo_beneficio_idField = value;
                this.RaisePropertyChanged("tipo_beneficio_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_beneficio_idSpecified {
            get {
                return this.tipo_beneficio_idFieldSpecified;
            }
            set {
                this.tipo_beneficio_idFieldSpecified = value;
                this.RaisePropertyChanged("tipo_beneficio_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoBeneficio", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoBeneficioRequest {
        
        public listarTodosTipoBeneficioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoBeneficioResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoBeneficioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO[] @return;
        
        public listarTodosTipoBeneficioResponse() {
        }
        
        public listarTodosTipoBeneficioResponse(KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoBeneficio", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoBeneficioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoBeneficioId;
        
        public obtenerPorIdTipoBeneficioRequest() {
        }
        
        public obtenerPorIdTipoBeneficioRequest(int tipoBeneficioId) {
            this.tipoBeneficioId = tipoBeneficioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoBeneficioResponse", WrapperNamespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoBeneficioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kawkiwebws.services.kawkiweb.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO @return;
        
        public obtenerPorIdTipoBeneficioResponse() {
        }
        
        public obtenerPorIdTipoBeneficioResponse(KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiposBeneficioChannel : KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiposBeneficioClient : System.ServiceModel.ClientBase<KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio>, KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio {
        
        public TiposBeneficioClient() {
        }
        
        public TiposBeneficioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiposBeneficioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposBeneficioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposBeneficioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio.listarTodosTipoBeneficio(KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest request) {
            return base.Channel.listarTodosTipoBeneficio(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO[] listarTodosTipoBeneficio() {
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest();
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse retVal = ((KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio)(this)).listarTodosTipoBeneficio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse> KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio.listarTodosTipoBeneficioAsync(KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest request) {
            return base.Channel.listarTodosTipoBeneficioAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioResponse> listarTodosTipoBeneficioAsync() {
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposBeneficio.listarTodosTipoBeneficioRequest();
            return ((KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio)(this)).listarTodosTipoBeneficioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio.obtenerPorIdTipoBeneficio(KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest request) {
            return base.Channel.obtenerPorIdTipoBeneficio(request);
        }
        
        public KawkiWebBusiness.KawkiWebWSTiposBeneficio.tiposBeneficioDTO obtenerPorIdTipoBeneficio(int tipoBeneficioId) {
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest();
            inValue.tipoBeneficioId = tipoBeneficioId;
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse retVal = ((KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio)(this)).obtenerPorIdTipoBeneficio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse> KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio.obtenerPorIdTipoBeneficioAsync(KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest request) {
            return base.Channel.obtenerPorIdTipoBeneficioAsync(request);
        }
        
        public System.Threading.Tasks.Task<KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioResponse> obtenerPorIdTipoBeneficioAsync(int tipoBeneficioId) {
            KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest inValue = new KawkiWebBusiness.KawkiWebWSTiposBeneficio.obtenerPorIdTipoBeneficioRequest();
            inValue.tipoBeneficioId = tipoBeneficioId;
            return ((KawkiWebBusiness.KawkiWebWSTiposBeneficio.TiposBeneficio)(this)).obtenerPorIdTipoBeneficioAsync(inValue);
        }
    }
}
